eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:${server.port}/eureka/
    instance:
        hostname: localhost
server:
    port: 1001
spring:
    application:
        name: gateway-x-server-center
